### ISSUE TITLE
[QUESTION] Use as generic path converter

### ISSUE THREAD

**Issue by joaopluigi** [hangxingliu/wslgit#4]
Hey,

First of all, thanks for this. It's working very well, saved my life 😄 

I'm wondering if is possible to use for other WSL executables (e.g `python`), so they can be also integrated to Windows VSCode.

**Comment by hangxingliu** [comment]
It is a good idea but implement a exact generic path converter is hard.

Because it is hard to know which part of output should be converted. For example, you mounted your drive D on `/d/` in  WSL. And there have `/a/b/c/d/e/f/g` in output of your python script. Then the converter be convert in to `/a/b/c/D:\e/f/g`.

And I will added some example converter scripts in this repo likes `wsl-python`, `wsl-node` and `wsl-php`  for experimental.

**Comment by joaopluigi** [comment]
Thanks for the answer. Just to give some context I was trying to be able to Run & Debug python applications using VSCode Python Extension

However, this extension try to run python code on the VSCode integrated terminal (or external if configured), which is, in my case, WSL Bash. For that reason, I found that it's useless to have a `.bat` converter, since the VSCode will try to run the following code on a WSL Terminal

```
cd "c:\apps\hh" ; env "PYTHONIOENCODING=UTF-8" "PYTHONUNBUFFERED=1" "C:\<PATH>\python.bat" "c:\Users\<USER>\.vscode\extensions\ms-python.python-2019.1.0\pythonFiles\ptvsd_launcher.py" --default --client --host localhost --port 61092 "c:\<APP_DIR>\.vscode\launch.json"
``` 

and, ofc, it will fail.

Just for curiosity, the solution for Debugging that I found was to import `ptsvd` in code and use the `Attach (Remote Debug)` configuration:

`app.py`
```python
# Enable Debugging
import ptvsd
print("Waiting for debugger attach...")
ptvsd.enable_attach(address=('localhost', 5678), redirect_output=True)
ptvsd.wait_for_attach()
breakpoint()
```

`launch.json`
```json
{
  "name": "Attach (Remote Debug)",
  "type": "python",
  "request": "attach",
  "port": 5678,
   "host": "localhost",
   "pathMappings": [{
      "localRoot": "${workspaceFolder}",
      "remoteRoot": "${file}"
    }]
}
```

This issue can be closed.
